[versions]
aboutlibraries = "11.6.3"
activity-compose = "1.10.1"
adaptive = "1.1.0"
androidx-camera = "1.4.2"
appcompat = "1.7.1"
av-wrapper = "0.1.0"
biometric = "1.1.0"
coil = "2.7.0"
compose-bom = "2025.03.01"
compose-destinations = "1.10.2"  # correct version depends on compose version, see https://github.com/raamcosta/compose-destinations?tab=readme-ov-file#2-add-the-dependencies
constraintlayout-compose = "1.1.1"
core-ktx = "1.16.0"
core-splashscreen = "1.0.1"
devtools-ksp = "2.2.0-2.0.2" # keep in sync with 'kotlin' [libs.versions.toml] and 'kotlinVersion' [build-logic/build.gradle.kts]
didresolver = "2.0.0"
espresso-core = "3.6.1"
espresso-intents = "3.6.1"
hilt = "2.56.2"
hilt-compiler = "1.2.0"
hilt-navigation-compose = "1.2.0"
integrity = "1.4.0"
java-json-canonicalization = "1.1"
json-path = "2.9.0"
json-schema-validator = "1.5.8"
junit-bom = "5.13.2"
junit5-mannodermaus = "1.13.1.0"
konsist = "0.17.3"
kotlin = "2.2.0" # keep in sync with 'devtools-ksp' [libs.versions.toml] and 'kotlinVersion' [build-logic/build.gradle.kts]
kotlin-reflect = "2.1.20"
kotlin-result = "2.0.1"
kotlinx-coroutines-test = "1.10.2"
kotlinx-serialization-json = "1.9.0"
ktor = "3.1.3"
lifecycle-runtime-compose = "2.9.1"
lottie-compose = "6.6.7"
mockk = "1.14.4"
nimbus-jose-jwt = "10.3.1"
qrcode-kotlin = "4.5.0"
room = "2.7.2"
runner = "1.6.2"
security-crypto = "1.0.0"
slf4j-android = "1.7.36"
slf4j-nop = "2.0.17"
sqlcipher-android = "4.9.0"
timber = "5.0.1"
ui-automator = "2.3.0"
zxing-cpp = "2.3.0"

[libraries]

aboutlibraries-compose = { module = "com.mikepenz:aboutlibraries-compose", version.ref = "aboutlibraries" }
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "core-splashscreen" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-espresso-intents = { module = "androidx.test.espresso:espresso-intents", version.ref = "espresso-intents" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-runtime-compose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
androidx-ui-automator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "ui-automator" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
av-wrapper = { module = "ch.admin.foitt.avwrapper:avwrapper", version.ref = "av-wrapper" }
coil = { module = "io.coil-kt:coil-base", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
compose-destinations = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }
didresolver = { module = "io.github.swiyu-admin-ch.didresolver:didresolver-android", version.ref = "didresolver" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
integrity = { module = "com.google.android.play:integrity", version.ref = "integrity" }
java-json-canonicalization = { module = "io.github.erdtman:java-json-canonicalization", version.ref = "java-json-canonicalization" }
json-path = { module = "com.jayway.jsonpath:json-path", version.ref = "json-path" }
json-schema-validator = { module = "com.networknt:json-schema-validator", version.ref = "json-schema-validator" }
konsist = { module = "com.lemonappdev:konsist", version.ref = "konsist" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin-reflect" }
kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlin-result" }
kotlin-result-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version.ref = "kotlin-result" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie-compose" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "nimbus-jose-jwt" }
qrcode-kotlin = { module = "io.github.g0dkar:qrcode-kotlin", version.ref = "qrcode-kotlin" }
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4j-android" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "slf4j-nop" }
sqlcipher-android = { module = "net.zetetic:sqlcipher-android", version.ref = "sqlcipher-android" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
zxing-cpp = { module = "io.github.zxing-cpp:android", version.ref = "zxing-cpp" }

# Compose BOM
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test-junit = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

# Junit BOM
junit-jupiter-bom = { module = "org.junit:junit-bom", version.ref = "junit-bom" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine" }

# used in androidx-camera bundle
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camera" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidx-camera" }

# used in ktor bundle
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

[bundles]
androidx-camera = ["androidx-camera-camera2", "androidx-camera-core", "androidx-camera-lifecycle", "androidx-camera-view"]
ktor = ["ktor-client-core", "ktor-client-content-negotiation", "ktor-client-okhttp", "ktor-client-logging", "ktor-serialization-kotlinx-json"]

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "junit5-mannodermaus" }
room = { id = "androidx.room", version.ref = "room" }
